'use client';
import { useEffect, useRef, useState } from 'react';
import * as Dialog from '@radix-ui/react-dialog';
import { Activity, ArrowUpRight, BarChart3, Bot, Boxes, Check, ChevronRight, CircleDollarSign, Coffee, Megaphone, Send, ShieldCheck, Sparkles, Users, X } from 'lucide-react';
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis, Legend } from 'recharts';
import { Agent, Department, Metric, monthly, revenue, respond, yearly } from '@/lib/mock-data';
export const icons = { Sales: BarChart3, Finance: CircleDollarSign, Marketing: Megaphone, Compliance: ShieldCheck, Inventory: Boxes, HR: Users };
export function AgentIcon({name,size=20}:{name:string;size?:number}) { const Icon=icons[name as Department]||Bot; return <span className={`agent-icon ${name.toLowerCase().replace(' ','-')}`}><Icon size={size}/></span>; }
export function Badge({children,tone='neutral'}:{children:React.ReactNode;tone?:string}) {return <span className={`badge ${tone}`}>{children}</span>;}
export function AgentStatusBadge({agent}:{agent:Agent}) {return <Badge tone={agent.name==='HR'?'green':agent.name==='Marketing'?'green':agent.name==='Finance'?'red':'amber'}>{agent.status}</Badge>;}
export function MetricCard({metric,index=0,onClick}:{metric:Metric;index?:number;onClick?:()=>void}) {const Icon=[CircleDollarSign,Activity,Boxes,BarChart3,Users,ShieldCheck][index%6]; return <button className="metric-card" onClick={onClick}><div className="metric-label">{metric.label}<Icon size={16}/></div><div className="metric-number">{metric.value}{/M|K/.test(metric.value)&&<small>VND</small>}</div><div className="metric-footer"><span className={metric.positive?'positive':'negative'}>{metric.change.startsWith('+')&&<ArrowUpRight size={13}/>} {metric.change}</span><span>{metric.note||'vs. previous period'}</span></div><div className={`metric-spark ${metric.positive?'':'down'}`}><svg viewBox="0 0 100 20" preserveAspectRatio="none"><path d={index%2?'M0 18 L10 13 L20 15 L30 8 L40 12 L50 7 L60 11 L70 4 L80 6 L90 2 L100 4':'M0 16 L10 18 L20 11 L30 14 L40 9 L50 11 L60 5 L70 8 L80 3 L90 6 L100 1'} fill="none" stroke="currentColor" strokeWidth="1.7"/></svg></div></button>; }
export function HealthScore({score=82,small=false}:{score?:number;small?:boolean}) {return <div className={`health-ring ${small?'small':''}`}><svg viewBox="0 0 120 120"><circle cx="60" cy="60" r="50" className="ring-track"/><circle cx="60" cy="60" r="50" className="ring-value" strokeDasharray={`${score*3.14} 314`} transform="rotate(-90 60 60)"/></svg><div><strong>{score}</strong><span>/ 100</span></div></div>;}
export function Panel({title,subtitle,action,children,className=''}:{title?:string;subtitle?:string;action?:React.ReactNode;children:React.ReactNode;className?:string}) {return <section className={`panel ${className}`}>{title&&<div className="panel-heading"><div><h2>{title}</h2>{subtitle&&<p>{subtitle}</p>}</div>{action}</div>}{children}</section>;}
export function EmptyState({title,body}:{title:string;body:string}) {return <div className="empty-state"><Check size={30}/><h3>{title}</h3><p>{body}</p></div>;}
export function Modal({open,onClose,title,children,wide=false,drawer=false}:{open:boolean;onClose:()=>void;title:string;children:React.ReactNode;wide?:boolean;drawer?:boolean}) {return <Dialog.Root open={open} onOpenChange={v=>!v&&onClose()}><Dialog.Portal><Dialog.Overlay className="modal-overlay"/><Dialog.Content className={`modal ${wide?'wide':''} ${drawer?'drawer':''}`} aria-describedby={undefined}><div className="modal-head"><Dialog.Title>{title}</Dialog.Title><Dialog.Close aria-label="Close dialog" className="icon-button"><X size={20}/></Dialog.Close></div><div className="modal-body">{children}</div></Dialog.Content></Dialog.Portal></Dialog.Root>;}
export function RevenueChart({range='30 Days',finance=false}:{range?:string;finance?:boolean}) {const data=range==='7 Days'?revenue.slice(-7):range==='3 Months'?monthly:range==='1 Year'?yearly:revenue;return <div className="chart-wrap"><ResponsiveContainer width="100%" height="100%" minWidth={0}><AreaChart data={data} margin={{left:-20,right:6,top:15,bottom:0}}><defs><linearGradient id="revenue-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#368764" stopOpacity={0.15}/><stop offset="100%" stopColor="#368764" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 4" vertical={false} stroke="#e8ece9"/><XAxis dataKey="day" axisLine={false} tickLine={false} minTickGap={40} tick={{fontSize:12,fill:'#87928c'}}/><YAxis axisLine={false} tickLine={false} tickFormatter={v=>`${v}M`} tick={{fontSize:12,fill:'#87928c'}}/><Tooltip contentStyle={{borderRadius:12,border:'1px solid #e3e9e4',fontSize:13}} formatter={(v:number)=>[`${v.toFixed(1)}M VND`]}/><Area type="monotone" name={finance?'Expenses':'Previous period'} dataKey={finance?'expenses':'previous'} stroke="#c2cebd" strokeDasharray="5 5" fill="none" strokeWidth={2}/><Area type="monotone" name="Revenue" dataKey="revenue" stroke="#2e7755" fill="url(#revenue-fill)" strokeWidth={2.5}/></AreaChart></ResponsiveContainer></div>;}
export function Bars({data,keys=['value'],colors=['#27694e'],height=240}:{data:Record<string,string|number>[];keys?:string[];colors?:string[];height?:number}) {return <div style={{height,minWidth:0,width:'100%'}}><ResponsiveContainer width="100%" height="100%" minWidth={0}><BarChart data={data} margin={{left:-20,right:10,top:15}}><CartesianGrid strokeDasharray="3 4" vertical={false}/><XAxis dataKey="name" tick={{fontSize:12}} tickLine={false} axisLine={false}/><YAxis tick={{fontSize:12}} tickLine={false} axisLine={false}/><Tooltip contentStyle={{borderRadius:12,fontSize:13}}/>{keys.map((key,i)=><Bar key={key} dataKey={key} fill={colors[i]||'#b8d99a'} radius={[5,5,0,0]}/>)}{keys.length>1&&<Legend/>}</BarChart></ResponsiveContainer></div>;}
export function Donut({data}:{data:{name:string;value:number}[]}) {const colors=['#18583f','#5e9672','#a8ca90','#d2e5c1','#e7eee1'];return <div className="donut-layout"><div style={{width:200,height:200}}><ResponsiveContainer><PieChart><Pie data={data} dataKey="value" innerRadius={58} outerRadius={84} paddingAngle={3}>{data.map((d,i)=><Cell key={d.name} fill={colors[i%colors.length]}/>)}</Pie><Tooltip formatter={(v:number)=>`${v}M VND`}/></PieChart></ResponsiveContainer></div><div>{data.map((d,i)=><div className="legend-row" key={d.name}><i style={{background:colors[i%colors.length]}}/>{d.name}<strong>{d.value}M</strong></div>)}</div></div>;}
export function RangeTabs({value,onChange,extended=false}:{value:string;onChange:(v:string)=>void;extended?:boolean}) {return <div className="range-tabs">{['7 Days','30 Days','3 Months',...(extended?['1 Year']:[])].map(x=><button key={x} onClick={()=>onChange(x)} className={value===x?'selected':''}>{x}</button>)}</div>;}
export function AgentCard({agent,onClick,large=false}:{agent:Agent;onClick:()=>void;large?:boolean}) {return <button className={`agent-card ${large?'large':''}`} onClick={onClick}><div className="agent-card-top"><AgentIcon name={agent.name}/><span className="agent-score">{agent.score}<small>/100</small></span></div><h3>{agent.name} Agent</h3>{large&&<p className="agent-description">{agent.description}</p>}<AgentStatusBadge agent={agent}/><p>{agent.finding}</p><div className="agent-card-bottom"><span>{large?'Checked 2 minutes ago':'View agent'}</span><ChevronRight size={15}/></div></button>;}
export function LoadingAgentState({name='Manager AI'}:{name?:string}) {return <div className="thinking"><Sparkles size={16}/>{name} is analyzing<span className="typing"><i/><i/><i/></span></div>;}
interface Message {id:number;role:'user'|'assistant';text:string;tags?:string[]}
export function ChatInterface({department,initialPrompt,compact=false,onTask}:{department?:Department;initialPrompt?:string;compact?:boolean;onTask?:(title:string)=>void}) {
 const [messages,setMessages]=useState<Message[]>([]); const [input,setInput]=useState(''); const [loading,setLoading]=useState(false); const end=useRef<HTMLDivElement>(null); const sent=useRef(''); const timer=useRef<ReturnType<typeof setTimeout>|null>(null);
 const send=(query:string)=>{if(!query.trim()||loading)return;setInput('');setMessages(v=>[...v,{id:Date.now(),role:'user',text:query}]);setLoading(true);timer.current=setTimeout(()=>{const reply=respond(query,department);setMessages(v=>[...v,{id:Date.now(),role:'assistant',...reply}]);setLoading(false);},1100);};
 useEffect(()=>{if(initialPrompt&&sent.current!==initialPrompt){sent.current=initialPrompt;send(initialPrompt);}},[initialPrompt]);
 useEffect(()=>()=>{if(timer.current)clearTimeout(timer.current);},[]);
 useEffect(()=>{if(messages.length)end.current?.scrollIntoView({behavior:'smooth',block:'nearest'});},[messages,loading]);
 const suggestions=department?[`What needs attention in ${department.toLowerCase()}?`,department==='Compliance'?'What do I need for the VAT declaration?':department==='Marketing'?'Which product should we promote?':`What should I do next?`]:['What needs my attention today?','Why did profit decrease?','Are we on track this month?','Which department has problems?','What should I focus on this week?','Which product should we promote?','Can we afford another employee?'];
 return <div className={`chat-interface ${compact?'compact':''}`}><div className="chat-messages">{!messages.length&&<div className="chat-welcome"><span className="ai-orb"><Sparkles size={30}/></span><Badge tone="green">{department?`${department} specialist`:'YOUR BUSINESS, CONNECTED'}</Badge><h2>{department?`Let’s talk ${department.toLowerCase()}.`:'One conversation. Your whole business.'}</h2><p>{department?'Ask about the latest findings, understand a change, or plan your next action.':'I bring together insights from all six agents to help you make your next move with confidence.'}</p><div className="prompt-grid">{suggestions.map(p=><button key={p} onClick={()=>send(p)}><Sparkles size={14}/>{p}<ChevronRight size={14}/></button>)}</div></div>}{messages.map(msg=><div className={`chat-message ${msg.role}`} key={msg.id}><span className="message-avatar">{msg.role==='user'?'TL':<Sparkles size={18}/>}</span><div><strong>{msg.role==='user'?'Thang Le':department?`${department} Agent`:'Manager AI'}</strong><div className="message-text">{msg.text}</div>{msg.tags&&<div className="message-tags">{msg.tags.map(t=><Badge tone="green" key={t}>{t}</Badge>)}</div>}{msg.role==='assistant'&&onTask&&<button className="text-button" onClick={()=>onTask(department?`Review ${department} recommendations`:'Review Supplier A pricing')}>Add recommended action to tasks <ChevronRight size={14}/></button>}</div></div>)}{loading&&<LoadingAgentState name={department?`${department} Agent`:'Manager AI'}/>}<div ref={end}/></div><form className="chat-input" onSubmit={e=>{e.preventDefault();send(input);}}><Sparkles size={19}/><input aria-label={`Ask ${department||'Manager AI'}`} placeholder={department?`Ask your ${department} Agent…`:'Ask anything about your business…'} value={input} onChange={e=>setInput(e.target.value)}/><button className="send-button" disabled={!input.trim()||loading} aria-label="Send message"><Send size={17}/></button></form><div className="chat-disclaimer">Simulated AI · Based on Lotus Coffee demo data · Always review recommendations</div></div>;
}
export function Brand({small=false}:{small?:boolean}) {return <div className={`brand ${small?'small':''}`}><span className="brand-mark"><span/><span/><span/></span>{!small&&<span>FabCommand<span className="brand-period">.</span></span>}</div>;}
