export type Department = 'Sales' | 'Finance' | 'Marketing' | 'Compliance' | 'Inventory' | 'HR';
export type TaskStatus = 'To Do' | 'In Progress' | 'Done';
export interface Metric { label: string; value: string; change: string; positive?: boolean; note?: string }
export interface Agent { name: Department; score: number; status: string; description: string; finding: string; reason: string; action: string; metrics: Metric[]; }
export interface Task { id: string; title: string; department: Department; priority: 'High' | 'Medium' | 'Opportunity'; due: string; status: TaskStatus; }
export interface Notice { id: number; title: string; body: string; department: Department; level: 'Critical' | 'Warnings' | 'Opportunities' | 'Information'; time: string; }
export interface Campaign { id: number; name: string; offer: string; facebook: string; instagram: string; budget: number; time: string; status: 'Draft' | 'Active' | 'Scheduled'; }
export const company = { name: 'Lotus Coffee', manager: 'Thang Le', location: 'Ho Chi Minh City', tagline: 'See the whole business. Know your next move.' };
export const metrics: Metric[] = [
 {label:'Monthly revenue',value:'154.2M',change:'+8.4%',positive:true,note:'vs. last month'},
 {label:'Net profit',value:'47.8M',change:'+12.1%',positive:true,note:'vs. last month'},
 {label:'Cash balance',value:'96.3M',change:'Healthy',positive:true,note:'2.3 months runway'},
 {label:'Orders',value:'1,284',change:'−5.2%',positive:false,note:'vs. last month'},
 {label:'Customers',value:'782',change:'+6.7%',positive:true,note:'vs. last month'},
 {label:'Open issues',value:'4',change:'2 high priority',positive:false,note:'Needs your attention'}
];
const m=(label:string,value:string,change:string,positive=true):Metric=>({label,value,change,positive});
export const agents: Agent[] = [
 {name:'Sales',score:86,status:'Attention',description:'Revenue, orders, products, and customer purchasing behavior.',finding:'Evening sales were 14% below normal yesterday.',reason:'Orders after 6 PM fell while daytime demand held steady. Coconut Coffee sales increased 27%, offsetting part of the decline.',action:'Review evening sales',metrics:[m('Revenue','154.2M','+8.4%'),m('Orders','1,284','−5.2%',false),m('Average order value','120.1K','+14.3%'),m('Conversion','12.4%','+0.8 pts'),m('Returning customers','38%','+3.2 pts')]},
 {name:'Finance',score:72,status:'Needs attention',description:'Expenses, cash flow, margins, and profitability.',finding:'Supplier expenses increased 21% this week.',reason:'Finance score is lower because supplier expenses increased and gross margin fell this week. Cash balance remains healthy.',action:'Review Supplier A pricing',metrics:[m('Revenue','154.2M','+8.4%'),m('Expenses','106.4M','+6.8%',false),m('Gross margin','30.8%','−3.4 pts',false),m('Net profit','47.8M','+12.1%'),m('Cash balance','96.3M','2.3 months runway')]},
 {name:'Marketing',score:79,status:'Opportunity found',description:'Growth opportunities, campaigns, and marketing performance.',finding:'Coconut Coffee engagement increased 38%.',reason:'Organic Coconut Coffee posts are outperforming other beverages. The afternoon audience is engaged but under-served by current campaigns.',action:'Create Coconut Coffee promotion',metrics:[m('Campaign reach','24,820','+18.6%'),m('Engagement','6.8%','+1.4 pts'),m('Conversion','4.2%','+0.6 pts'),m('Marketing spend','6.2M','Within budget'),m('Estimated ROAS','4.6×','+0.8×')]},
 {name:'Compliance',score:65,status:'Deadline approaching',description:'Tax obligations, invoices, and important deadlines.',finding:'VAT declaration is due in 6 days.',reason:'Two supporting documents are still missing from the demo VAT folder. There are no overdue obligations.',action:'Prepare VAT documents',metrics:[m('Upcoming obligations','3','Next 30 days'),m('Documents ready','8 / 10','2 outstanding',false),m('Overdue filings','0','On track'),m('Invoices reconciled','96%','+4 pts')]},
 {name:'Inventory',score:84,status:'Low stock alert',description:'Stock levels, product movement, and supplier availability.',finding:'Oat milk is projected to run out in 4 days.',reason:'Oat milk demand increased with specialty beverage sales. Coffee beans remain well stocked, but croissants should be reordered soon.',action:'Order oat milk',metrics:[m('Inventory value','28.6M','+4.1%'),m('Low stock products','2','Action needed',false),m('Stock turnover','4.8×','+0.4×'),m('Suppliers','6','All active')]},
 {name:'HR',score:91,status:'Running smoothly',description:'Staffing, attendance, scheduling, and labor costs.',finding:'Saturday afternoon may be understaffed.',reason:'Attendance is strong at 98.2% and overtime is within budget. One additional barista would cover Saturday’s 2–5 PM peak.',action:'Review Saturday staffing',metrics:[m('Employees working','8 / 12','Today'),m('Labor cost','32.4M','21% of revenue'),m('Attendance','98.2%','+1.2 pts'),m('Overtime','12 hrs','−4 hrs'),m('Average hours','36 hrs','Per employee')]}
];
export const revenue = Array.from({length:30},(_,i)=>({day:`Sep ${i+1}`,revenue:[3.7,4.2,3.9,4.8,4.4,5.7,6.2,4.8,4.2,5.1,4.7,5.9,6.8,6.1,4.9,5.3,4.7,5.8,6.4,7.2,6.5,5.4,5.8,5.1,6.3,6.8,7.4,6.2,5.9,6.7][i],previous:[3.3,3.8,3.6,4.1,4.3,4.9,5.6,4.4,4.0,4.5,4.2,5.3,5.8,5.5,4.6,4.7,4.4,5.1,5.6,6.0,5.7,4.8,5.0,4.6,5.2,5.8,6.1,5.3,5.2,5.8][i],expenses:2.8+(i%7)*0.3}));
export const monthly = [{day:'Jul',revenue:131.1,previous:121,expenses:94.2},{day:'Aug',revenue:142.25,previous:129,expenses:99.6},{day:'Sep',revenue:154.2,previous:137.2,expenses:106.4}];
export const yearly = Array.from({length:12},(_,i)=>({day:['Oct','Nov','Dec','Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep'][i],revenue:98+i*4.8+(i%3)*6,previous:90+i*4,expenses:68+i*3.4}));
export const hourly = [{name:'8 AM',value:142},{name:'10 AM',value:186},{name:'12 PM',value:220},{name:'2 PM',value:128},{name:'4 PM',value:168},{name:'6 PM',value:134},{name:'8 PM',value:89}];
export const products = [{name:'Coconut Coffee',value:42.8,orders:356,margin:61,growth:27},{name:'Vietnamese Milk Coffee',value:38.6,orders:322,margin:58,growth:8},{name:'Matcha Latte',value:28.4,orders:236,margin:54,growth:12},{name:'Cold Brew',value:24.1,orders:200,margin:65,growth:6},{name:'Croissant',value:20.3,orders:170,margin:42,growth:-3}];
export const expenses = [{name:'Ingredients',value:42.6},{name:'Labor',value:32.4},{name:'Rent',value:18},{name:'Marketing',value:6.2},{name:'Utilities',value:7.2}];
export const inventory = [{name:'Coffee Beans',stock:'42 kg',days:12,status:'Healthy'},{name:'Oat Milk',stock:'18 cartons',days:4,status:'Low stock'},{name:'Coconut Syrup',stock:'23 bottles',days:7,status:'Watch'},{name:'Croissants',stock:'65 units',days:3,status:'Reorder soon'}];
export const staffing = ['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map((name,i)=>({name,scheduled:[7,7,8,8,9,7,9][i],needed:[7,7,7,8,9,10,9][i]}));
export const employees = [{name:'Minh Tran',role:'Barista',hours:36},{name:'Anh Pham',role:'Shift lead',hours:38},{name:'Bao Le',role:'Barista',hours:32},{name:'Trang Vo',role:'Front of house',hours:36}];
export const obligations = [{name:'VAT Declaration',days:6,risk:'High',documents:['Sales VAT invoices','Purchase VAT invoices','Revenue reconciliation','Supplier A invoice','Bank payment summary'],missing:['Supplier A invoice','Bank payment summary']},{name:'Electronic Invoice Report',days:12,risk:'Medium',documents:['Invoice export','Cancelled invoice register','Reconciliation summary'],missing:['Reconciliation summary']},{name:'Personal Income Tax',days:24,risk:'Low',documents:['Payroll summary','Employee deductions','Withholding ledger'],missing:[]}];
export const initialTasks: Task[] = [
 {id:'t1',title:'Prepare VAT documents',department:'Compliance',priority:'High',due:'Oct 5',status:'To Do'},
 {id:'t2',title:'Review Supplier A pricing',department:'Finance',priority:'Medium',due:'Sep 30',status:'To Do'},
 {id:'t3',title:'Order oat milk',department:'Inventory',priority:'High',due:'Oct 2',status:'In Progress'},
 {id:'t4',title:'Create Coconut Coffee promotion',department:'Marketing',priority:'Opportunity',due:'Oct 1',status:'To Do'},
 {id:'t5',title:'Review Saturday staffing',department:'HR',priority:'Medium',due:'Oct 2',status:'Done'}
];
export const notifications: Notice[] = [
 {id:1,title:'Oat milk below safe inventory level',body:'18 cartons remain. Create a purchase task for 36 cartons before Friday.',department:'Inventory',level:'Critical',time:'8 min ago'},
 {id:2,title:'Today’s sales are 16% below forecast',body:'The morning is quieter than expected. Monitor the lunch period before adjusting staffing.',department:'Sales',level:'Warnings',time:'12 min ago'},
 {id:3,title:'Coconut Coffee demand increased 24%',body:'An afternoon promotion could capture growing demand for high-margin beverages.',department:'Marketing',level:'Opportunities',time:'20 min ago'},
 {id:4,title:'VAT filing due in 6 days',body:'Two documents are still outstanding. Review the preparation checklist.',department:'Compliance',level:'Warnings',time:'30 min ago'},
 {id:5,title:'Cash may approach your safety threshold',body:'Next month’s planned expenses could reduce cash below 80M VND. Review supplier payment timing.',department:'Finance',level:'Warnings',time:'1 hour ago'},
 {id:6,title:'September reconciliation completed',body:'The demo accounting data is up to date. All department agents have refreshed their analysis.',department:'Finance',level:'Information',time:'2 hours ago'}
];
export const activity = [{time:'08:49',agent:'Marketing',text:'Found a Coconut Coffee promotion opportunity.'},{time:'08:47',agent:'Manager AI',text:'Updated today’s priority list.'},{time:'08:46',agent:'Finance',text:'Detected increasing supplier costs.'},{time:'08:45',agent:'Inventory',text:'Forecast oat milk to run out in 4 days.'},{time:'08:43',agent:'Sales',text:'Detected a 14% decrease in evening orders.'}];
export const initialCampaigns: Campaign[] = [{id:1,name:'Weekend Coffee Ritual',offer:'Coffee + croissant bundle',facebook:'Slow weekends, good coffee. Find your favorite corner at Lotus Coffee.',instagram:'Your weekend ritual starts here. ☕ #LotusCoffee',budget:2500000,time:'Saturday & Sunday, 8–11 AM',status:'Active'},{id:2,name:'Loyalty, One Cup at a Time',offer:'Double loyalty points',facebook:'More reasons to come back. Earn double points every Tuesday.',instagram:'Your usual, with a little extra. 🌿 #LotusRegulars',budget:1200000,time:'Tuesday, all day',status:'Active'}];
export const campaignDraft: Campaign = {id:3,name:'Coconut Coffee Afternoon Boost',offer:'10% off Coconut Coffee from 2–5 PM',facebook:'Need an afternoon refresh? 🥥☕ Enjoy 10% off our Coconut Coffee from 2–5 PM today. Your little escape awaits at Lotus Coffee.',instagram:'An afternoon worth slowing down for. 🥥☕ Coconut Coffee, 10% off, 2–5 PM. #LotusCoffee #SaigonCoffee',budget:1500000,time:'Weekdays, 2–5 PM',status:'Draft'};
export const reports = [{name:'Daily Report',period:'September 29, 2026',summary:'Today’s priorities, sales pulse, and department alerts.'},{name:'Weekly Manager Report',period:'September 22–28, 2026',summary:'Performance trends and the decisions that matter this week.'},{name:'Monthly Business Review',period:'September 2026',summary:'Your complete month in focus. Growth, risks, and next steps.'}];
export const prompts = ['What needs my attention today?','Why did profit decrease?','Are we on track this month?','Which department has problems?','What should I focus on this week?','Which product should we promote?','Can we afford another employee?'];
export function respond(query:string,department?:Department):{text:string;tags:string[]} {
 const q=query.toLowerCase();
 if(department==='Compliance'||/vat|tax|document/.test(q))return {text:'For the demo VAT declaration due in 6 days, prepare:\n\n1. Sales and purchase VAT invoices.\n2. Revenue reconciliation for the period.\n3. Supplier A’s missing invoice.\n4. Bank payment summary.\n\nEight of ten documents are ready. Assign the two missing items to Finance today, then have your accountant review the filing.\n\nDemo guidance only — not professional tax advice. Dates are illustrative.',tags:['Compliance Agent','Finance Agent']};
 if(/profit|margin|supplier|cost/.test(q))return {text:'Profit margin decreased from 34.2% to 30.8%, even though total monthly profit grew 12.1%.\n\nThe Finance Agent identified two main causes:\n1. Ingredient costs increased 11%. Supplier A’s weekly bill rose 21%.\n2. Discount campaigns reduced average order value by 6% within the discounted segment.\n\nThe Sales Agent also found a larger share of lower-margin products.\n\nNext steps: review Supplier A pricing, reduce discounts on high-demand items, and promote Coconut Coffee, which has a 61% gross margin.',tags:['Finance Agent','Sales Agent']};
 if(/employee|hire|staff|saturday/.test(q)||department==='HR')return {text:'A full-time barista would cost approximately 8.5M VND per month including the demo allowance. Cash reserves cover 2.3 months of operating expenses.\n\nDemand is concentrated on Saturday from 2–5 PM, when 10 staff are needed but only 7 are scheduled. Start by moving one available barista’s shift and adding part-time coverage.\n\nReview two weeks of demand before committing to a full-time hire.',tags:['HR Agent','Finance Agent','Sales Agent']};
 if(/promot|product|campaign|coconut/.test(q)||department==='Marketing')return {text:'Coconut Coffee is your strongest promotion candidate.\n\n• Sales increased 27% this week.\n• Engagement increased 38%.\n• Gross margin is 61%; a 10% discount remains profitable.\n• Ingredients can cover approximately 350 additional orders.\n\nRun “Coconut Coffee Afternoon Boost” from 2–5 PM with a 1.5M VND test budget. Review order lift after three days before expanding.',tags:['Sales Agent','Marketing Agent','Finance Agent','Inventory Agent']};
 if(/stock|milk|inventory/.test(q)||department==='Inventory')return {text:'Oat milk is the immediate stock risk: 18 cartons remain, or about 4 days of demand.\n\nOrder 36 cartons before Friday. Coconut Syrup has 7 days of cover, and coffee beans have 12. Croissants have 3 days of cover and should be reviewed with the next bakery delivery.\n\nA purchase task keeps this visible in your Action Center.',tags:['Inventory Agent','Sales Agent']};
 if(/track|month/.test(q))return {text:'You’re broadly on track. Monthly revenue is 154.2M VND (+8.4%) and net profit is 47.8M VND (+12.1%). Business health is 82/100.\n\nThe main caution is order volume, down 5.2%. Higher average order value currently offsets this, but evening demand needs attention.\n\nFocus this week on supplier pricing, the afternoon Coconut Coffee opportunity, and completing VAT documents.',tags:['Manager AI','Sales Agent','Finance Agent']};
 if(department==='Sales')return {text:'Evening sales were 14% below the 30-day average yesterday. The decline was concentrated after 6 PM; daytime demand stayed steady.\n\nCoconut Coffee grew 27%, while croissant orders softened. Test an evening beverage bundle for three days and compare orders and margin against similar weekdays.',tags:['Sales Agent','Marketing Agent']};
 return {text:'Here’s what needs your attention today, Thang.\n\n1. Protect your margin. Supplier A expenses rose 21%; review the latest ingredient prices with Finance.\n2. Avoid a stockout. Order 36 cartons of oat milk before Friday.\n3. Prepare VAT documents. The demo deadline is in 6 days, with two documents missing.\n\nYour growth opportunity: Coconut Coffee sales are up 27%. A targeted 2–5 PM promotion can improve afternoon demand while preserving margin.\n\nI’ve combined all six agents’ findings. Start with supplier pricing, then review the promotion recommendation.',tags:['Finance Agent','Inventory Agent','Compliance Agent','Marketing Agent']};
}
